### ISSUE TITLE
Negotiations not deleting when there are no more customers

### ISSUE THREAD

**Issue by gallexi** [galantlex/megabites#3]

**Comment by gallexi** [comment]
Now that seems to be working, at leas in local host, but it's not pushing to Heroku correctly. Heroku app crashed when we attempted that.

**Comment by hannahpersampieri** [comment]
Just tested on go.tufts.io/megabites, seems to be working okay.

**Comment by gallexi** [comment]
Yep, fixed and forgot to close issue. All good!
